version: '3.7'

services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
    webserver:
        build:
            context: ../airflow/
            dockerfile: ../docker/Dockerfile-webserver
        image: airflow_webserver
        container_name: airflow_webserver
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - $HOME/.aws/credentials:/usr/local/airflow/.aws/credentials:ro
        expose:
            - "8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        entrypoint: ["/entrypoint.sh", "webserver"]
    nginx:
        image: quay.io/dtan4/nginx-basic-auth-proxy:latest
        container_name: nginx_basic_auth
        ports:
          - "80:80"
          - "8090:8090"
        environment:
          - BASIC_AUTH_USERNAME=admin
          - BASIC_AUTH_PASSWORD=randompass
          - PROXY_PASS=http://webserver:8080
        depends_on:
          - webserver
