FROM airflow_webserver:latest

LABEL maintainer="szczepanik.antoni@gmail.com"

USER root

RUN pip3 install jupyterlab==1.2.3 \
	&& curl -sL https://deb.nodesource.com/setup_12.x | bash \
	&& apt-get install -y nodejs \
	&& jupyter labextension install jupyterlab_vim

USER airflow

EXPOSE 8889
