version: '3.7'

services:
    # add minio flag to support using minio in compose (also flats network)
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
    webserver:
        image: airflow_webserver
        container_name: airflow_webserver
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - USE_MINIO=true
        volumes:
            - $HOME/.aws/credentials:/usr/local/airflow/.aws/credentials:ro
            - ../airflow/dags:/usr/local/airflow/dags
            - ../airflow/deps:/usr/local/airflow/deps
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        entrypoint: ["/entrypoint.sh", "webserver"]
networks:
        default:
                external:
                        name: flats
