version: '3'

services:
  server:
    restart: always
    image: flats-server
    ports:
      - "5000:5000"
    volumes:
      - ./src:/src
    networks:
      - db
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgis/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - /home/antoni/flats-buckets/data:/var/lib/postgresql/data 
    networks:
      - db

volumes:
        src:

networks: 
  db:
    driver: bridge
