version: '3'

services:
  server:
    restart: always
    build: .
    ports:
      - "5000:5000"
    volumes:
      - src:/src
    networks:
      - db
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data:/var/lib/postgresql/data 
    networks:
      - db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
       PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
       PGADMIN_DEFAULT_PASSWORD: "admin"
       PGADMIN_LISTEN_PORT: 80
    ports:
        - "8080:80"
    tty: true
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - db

volumes:
        src:

networks: 
  db:
    driver: bridge


