version: '3'

services:
  server:
    restart: always
    image: flats_v2_server
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    networks:
      - db
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
#    volumes:
            #  - /home/antoni/postgres/data:/var/lib/postgresql/data 
    networks:
      - db

volumes:
        src:

networks: 
  db:
    driver: bridge
