CREATE DATABASE flats;
\c flats;
CREATE TYPE offer_type AS ENUM ('sale', 'rent');
CREATE TABLE offers (
	offer_id SERIAL NOT NULL,
	type__offer offer_type NOT NULL,
	balcony__offer BOOLEAN,
	building_height__offer SMALLINT CHECK (building_height__offer >= 0),
	building_material__offer SMALLINT CHECK (building_material__offer >= 0),
	building_type__offer SMALLINT CHECK (building_type__offer >= 0),
	building_year__offer SMALLINT CHECK (building_year__offer >= 0),
	conviniences__offer BOOLEAN,
	date_added__offer DATE,
	date_refreshed__offer DATE,
	desc_len__offer INTEGER CHECK (desc_len__offer >= 0),
	direct__offer BOOLEAN,
	equipment__offer SMALLINT CHECK (equipment__offer >= 0),
	flat_state__offer SMALLINT CHECK (flat_state__offer >=0),
	floor__offer SMALLINT CHECK (floor__offer >=0),
	heating__offer SMALLINT CHECK (heating__offer >=0),
	image_link__offer VARCHAR(300),
	lon__offer DOUBLE PRECISION CHECK(lon__offer >=0),
	lat__offer DOUBLE PRECISION CHECK(lat__offer >=0),
	market_type__offer BOOLEAN,
	media__offer BOOLEAN,
	offer_id__offer CHAR(100) UNIQUE,
	price__offer DOUBLE PRECISION CHECK (price__offer >=0),
	price_m2__offer DOUBLE PRECISION CHECK (price_m2__offer >=0),
	promotion_counter__offer SMALLINT CHECK (promotion_counter__offer >=0),
	room_n__offer SMALLINT CHECK (room_n__offer >=0),
	size__offer DOUBLE PRECISION CHECK (size__offer >=0),
	taras__offer BOOLEAN,
	title__offer VARCHAR(300),
	url__offer VARCHAR(300) UNIQUE,
	view_count__offer SMALLINT CHECK (view_count__offer >=0),
	water__offer BOOLEAN,
	floor_number__clean SMALLINT CHECK (floor_number__clean >=0),
	lift__clean BOOLEAN,
	basement__clean BOOLEAN,
	telecom__clean BOOLEAN,
	driveway__clean BOOLEAN,
	fence__clean BOOLEAN,
	parking_spot__clean BOOLEAN,
	furniture__clean BOOLEAN,
	kitchen_furniture__clean BOOLEAN,
	internet__clean BOOLEAN,
	gas__clean BOOLEAN,
	electricity__clean BOOLEAN,
	sewers__clean BOOLEAN,
	cluster_id__feature INTEGER CHECK (cluster_id__feature >=0),
	cluster_mean_price__feature DOUBLE PRECISION CHECK (cluster_mean_price__feature >=0),
	cluster_mean_price_m2__feature DOUBLE PRECISION CHECK (cluster_mean_price_m2__feature >=0),
	cluster_center_dist_km__feature DOUBLE PRECISION CHECK (cluster_center_dist_km__feature >=0),
	cluster_coords_factor__feature DOUBLE PRECISION CHECK (cluster_coords_factor__feature >=0),
	sale__prediction DOUBLE PRECISION CHECK (sale__prediction >=0),
	rent__prediction DOUBLE PRECISION CHECK (rent__prediction >=0),
	sale_price_diff__prediction DOUBLE PRECISION,
	rent_price_diff__prediction DOUBLE PRECISION
);
