from flask_restful import fields

OFFER_FIELDS = {
    'offer_id': fields.Integer,
    'type__offer': fields.String,
    'offer_id__offer': fields.String,
    'lat__offer': fields.Float,
    'lon__offer': fields.Float,
    'type__offer': fields.String,
    'offer_id__offer': fields.String,
    'lat__offer': fields.Float,
    'lon__offer': fields.Float,
    'balcony__offer': fields.Boolean,
    'building_height__offer': fields.Integer,
    'building_material__offer': fields.Integer,
    'building_type__offer': fields.Integer,
    'building_year__offer': fields.Integer,
    'conviniences__offer': fields.Boolean,
#    'date_added__offer': fields.DateTime(),
#    'date_refreshed__offer': fields.DateTime(),
    'desc_len__offer': fields.Integer,
    'direct__offer': fields.Boolean,
    'equipment__offer': fields.Integer,
    'flat_state__offer': fields.Integer,
    'floor__offer': fields.Integer,
    'heating__offer': fields.Integer,
    'image_link__offer': fields.String,
    'lon__offer': fields.Float,
    'lat__offer': fields.Float,
    'market_type__offer': fields.Boolean,
    'media__offer': fields.Boolean,
    'offer_id__offer': fields.String,
    'price__offer': fields.Float,
    'price_m2__offer': fields.Float,
    'promotion_counter__offer': fields.Integer,
    'room_n__offer': fields.Integer,
    'size__offer': fields.Float,
    'taras__offer': fields.Boolean,
    'title__offer': fields.String,
    'url__offer': fields.String,
    'view_count__offer': fields.Integer,
    'water__offer': fields.Boolean,
    'floor_number__clean': fields.Integer,
    'lift__clean': fields.Boolean,
    'basement__clean': fields.Boolean,
    'telecom__clean': fields.Boolean,
    'driveway__clean': fields.Boolean,
    'fence__clean': fields.Boolean,
    'parking_spot__clean': fields.Boolean,
    'furniture__clean': fields.Boolean,
    'kitchen_furniture__clean': fields.Boolean,
    'internet__clean': fields.Boolean,
    'gas__clean': fields.Boolean,
    'electricity__clean': fields.Boolean,
    'sewers__clean': fields.Boolean,
    'cluster_id__feature': fields.Integer,
    'cluster_mean_price__feature': fields.Float,
    'cluster_mean_price_m2__feature': fields.Float,
    'cluster_center_dist_km__feature': fields.Float,
    'cluster_coords_factor__feature': fields.Float,
    'sale__prediction': fields.Float,
    'rent__prediction': fields.Float,
    'sale_price_diff__prediction': fields.Float,
    'rent_price_diff__prediction': fields.Float,
}
