import datetime

from flask_restful import reqparse

from common import DT_FORMAT

post_parser = reqparse.RequestParser()
post_parser.add_argument('type__offer', type=str, required=True)
post_parser.add_argument('offer_id__offer', type=str, required=True)
post_parser.add_argument('lat__offer', type=float)
post_parser.add_argument('lon__offer', type=float)
post_parser.add_argument('balcony__offer', type=bool)
post_parser.add_argument('building_height__offer', type=int)
post_parser.add_argument('building_material__offer', type=int)
post_parser.add_argument('building_type__offer', type=int)
post_parser.add_argument('building_year__offer', type=int)
post_parser.add_argument('conviniences__offer', type=bool)
post_parser.add_argument('date_added__offer', type=lambda x: datetime.datetime.strptime(x, DT_FORMAT).date())
post_parser.add_argument('date_refreshed__offer', type=lambda x: datetime.datetime.strptime(x, DT_FORMAT).date())
post_parser.add_argument('desc_len__offer', type=int)
post_parser.add_argument('direct__offer', type=bool)
post_parser.add_argument('equipment__offer', type=int)
post_parser.add_argument('flat_state__offer', type=int)
post_parser.add_argument('floor__offer', type=int)
post_parser.add_argument('heating__offer', type=int)
post_parser.add_argument('image_link__offer', type=str)
post_parser.add_argument('lon__offer', type=float)
post_parser.add_argument('lat__offer', type=float)
post_parser.add_argument('market_type__offer', type=bool)
post_parser.add_argument('media__offer', type=bool)
post_parser.add_argument('offer_id__offer', type=str)
post_parser.add_argument('price__offer', type=float)
post_parser.add_argument('price_m2__offer', type=float)
post_parser.add_argument('promotion_counter__offer', type=int)
post_parser.add_argument('room_n__offer', type=int)
post_parser.add_argument('size__offer', type=float)
post_parser.add_argument('taras__offer', type=bool)
post_parser.add_argument('title__offer', type=str)
post_parser.add_argument('url__offer', type=str)
post_parser.add_argument('view_count__offer', type=int)
post_parser.add_argument('water__offer', type=bool)
post_parser.add_argument('floor_number__clean', type=int)
post_parser.add_argument('lift__clean', type=bool)
post_parser.add_argument('basement__clean', type=bool)
post_parser.add_argument('telecom__clean', type=bool)
post_parser.add_argument('driveway__clean', type=bool)
post_parser.add_argument('fence__clean', type=bool)
post_parser.add_argument('parking_spot__clean', type=bool)
post_parser.add_argument('furniture__clean', type=bool)
post_parser.add_argument('kitchen_furniture__clean', type=bool)
post_parser.add_argument('internet__clean', type=bool)
post_parser.add_argument('gas__clean', type=bool)
post_parser.add_argument('electricity__clean', type=bool)
post_parser.add_argument('sewers__clean', type=bool)
post_parser.add_argument('cluster_id__feature', type=int)
post_parser.add_argument('cluster_mean_price__feature', type=float)
post_parser.add_argument('cluster_mean_price_m2__feature', type=float)
post_parser.add_argument('cluster_center_dist_km__feature', type=float)
post_parser.add_argument('cluster_coords_factor__feature', type=float)
post_parser.add_argument('sale__prediction', type=float)
post_parser.add_argument('rent__prediction', type=float)
post_parser.add_argument('sale_price_diff__prediction', type=float)
post_parser.add_argument('rent_price_diff__prediction', type=float)
