

name: publish

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Build and sync with S3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: cd site && npm install
      
    - name: Build page
      run: cd site && npm run build
      
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-central-1

    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 rm --recursive s3://flats.antoniszczepanik.com/ --exclude "data.json"
        aws s3 sync site/build/ s3://flats.antoniszczepanik.com/
